# Generated by Django 6.0.3 on 2026-03-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="seat_in_rows",
            new_name="seats_in_row",
        ),
    ]
